sudo: required
language: c
compiler:
  - gcc
services:
  - docker
before_install:
  - docker pull linuxmaniac/pkg-kamailio-docker:jessie
script: docker run -v $TRAVIS_BUILD_DIR:/code:rw linuxmaniac/pkg-kamailio-docker:jessie /bin/bash -c "export CC=$CC; cd /code; ./test/travis/build_travis.sh"
branches:
  only:
    - 'master'
    - '/^4\.[0-9]+$/'
notifications:
  irc:
    channels:
      - "chat.freenode.net#kamailio-dev"
    on_success: never
    on_failure: always
  email:
    recipients:
      - sr-dev@lists.kamailio.org
    on_success: never
    on_failure: always
