sudo: required
language: c
compiler:
  - gcc
  - clang
services:
  - docker
before_install:
  - docker pull kamailio/pkg-kamailio-docker:4.4-stretch
script: docker run -v $TRAVIS_BUILD_DIR:/code:rw kamailio/pkg-kamailio-docker:5.0-stretch /bin/bash -c "export CC=$CC; cd /code; ./test/travis/build_travis.sh"
branches:
  only:
    - '/^4\.[0-9]+$/'
notifications:
  irc:
    channels:
      - "chat.freenode.net#kamailio-dev"
    on_success: never
    on_failure: always
  email:
    recipients:
      - sr-dev@lists.kamailio.org
    on_success: never
    on_failure: always
