---
name: cleanup packages
on:
  schedule:
    - cron: '0 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: kamailio-ci

jobs:
  x86_64:
    runs-on: ubuntu-latest
    permissions:
      packages: admin
    steps:
    - name: Delete untagged images
      uses: camargo/delete-untagged-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        package-name: ${{ env.IMAGE_NAME }}
