---
name: build
'on':
  push:
    branches:
      - master
      - '5.6'
      - '5.5'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kamailio/pkg-kamailio-docker:${{ github.ref_name }}-${{ matrix.distribution }}
      volumes:
        - ${{ github.workspace }}:/code
      env:
        DIST: ${{ matrix.distribution }}
        CC: ${{ matrix.compilier }}
    strategy:
      matrix:
        include:
          - distribution: bullseye
            compilier: gcc
          - distribution: bullseye
            compilier: clang
          - distribution: sid
            compilier: gcc
          - distribution: sid
            compilier: clang
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/gcc-problem-matcher@0.1
      - name: build
        run: |
          cd /code
          ./test/travis/build_travis.sh
        shell: bash
