---
name: build
'on':
  push:
    branches:
      - 6.1
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # to fetch code (actions/checkout)
    container:
      image: ghcr.io/kamailio/pkg-kamailio-docker:${{ github.ref_name }}-${{ matrix.distribution }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - ${{ github.workspace }}:/code
      env:
        DIST: ${{ matrix.distribution }}
        CC: ${{ matrix.compilier }}
    strategy:
      matrix:
        include:
          - distribution: trixie
            compilier: gcc
          - distribution: trixie
            compilier: clang
    steps:
      - uses: actions/checkout@v6
      - uses: ammaraskar/gcc-problem-matcher@0.3.0
      - name: build
        run: |
          cd /code
          ./test/travis/build_travis.sh
        shell: bash
